### ISSUE TITLE
balance issue

### ISSUE THREAD

**Issue by fedecaccia** [jimako1989/bitfinexpy#1]
Hi, congrats for the wapper, its very useful. I am trying to do the next:
keys=<KEY>
secrets=<SECRET>

bitfinex = bitfinexpy.API(environment="live", key=keys, secret_key=secrets)
walletBalances = bitfinex.wallet_balances()

and I have this error:

Traceback (most recent call last):
  File "bitfinexBot.py", line 12, in <module>
    walletBalances = bitfinex.wallet_balances()
  File "/home/cripto/bitfinexpy.py", line 282, in wallet_balances
    return self.request(endpoint, method='POST', payload_params=params)
  File "/home/cripto/bitfinexpy.py", line 369, in request
    raise BitfinexError(response.status_code,content)
  File "/home/cripto/bitfinexpy.py", line 434, in __init__
    msg = "BITFINEX API returned error code %s (%s) " % (status_code, error_response['error'])
KeyError: 'error'

I don't know what is happening, can you help me?

**Comment by tk42** [comment]
Hi! Thanks for reporting.
The request url of bitfinex was changed. So I fixed and merged. Try it!

FYI
Now I won't support this repo well, because the python exchange wrapper 'ccxt' is extremely great!
If you will connect to the exchange except bitfinex, you should try the module.
https://github.com/ccxt/ccxt

**Comment by fedecaccia** [comment]
Thanks for fixing it! I'am going to try also with the ccxt repo because I need solutions to other exchanges platforms, your answer really helps me.
